baseURL = "https://staging.madeofme.me/"
languageCode = "en-us"
title = "Made of Meme"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
SectionPagesMenu = "main"
Paginate = 50 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-85767008-3"
enableRobotsTXT = true
enableEmoji = true
#disqusShortname = "brewingcats"
publishDir = "docs"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.en]
    [languages.en.params]
      description = "Meme Inspired Merchandise"
  [languages.es]
    [languages.es.params]
      description = "Mercancía Inspirada por Memes"

[params]
  useGenericGdpr = false
  googleAnalytics = "UA-85767008-3"
  favicon = "images/favicon.ico"
  facebook = "https://www.facebook.com/profile.php?id=100091982683287"
  twitter = ""
  instagram = "https://www.instagram.com/made.of.me.me/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  logo = "/images/madeofmemebanner.png"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/mom.png"
  recent_posts_number = 15
  #mainSections = ["software", "uncategorized", "site"]
  env = "production"
  theme_color = '254, 227, 111' # This has to be RGB coordinates
  link_hover = '#ea6a47' # dark red
  siteRef = "brewingcats.com"
  #fbAppId = "100091982683287"
  #fbTokenId = "cb323292940db3edd2ab47777543b4f7"
  telemetryUrl = "https://us-central1-brewingcats.cloudfunctions.net/stagingLogger"
  telemetryDataUrl = "https://media.brewingcats.com/telemetry/"
  telemetryDataBaseName = "BrewingCats"
  telemetryDataEnv = "Staging"
  #telemetryDataEnv = "Production"
  #telemetryVizId = "viz1613956602843"
  #telemetryVizPre = "Br"
  #telemetryVizName = "BrewingCats-StagingTelemetry"
  #telemetryVizView = "Analysis"
  statsUrl = "https://us-central1-brewingcats.cloudfunctions.net/stats"
  siteEnv = "staging"
  referral = "https://brewingcats.com"
  useFooterStats = "true"
  useFooterReferral = "true"
  projectId = "staging-MadeOfMeme"
  siteVersion = "1.1"
